name: Build Android APK

on:
  push:
    branches:
      - main  # atau ganti ke 'master' jika itu nama branch-mu

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'  # Pastikan sesuai versi Gradle kamu

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: accessibility-bridge-apk
        path: app/build/outputs/apk/debug/*.apk